// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: OtpMigration.proto

package OtpMigration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_ALGORITHM_TYPE_UNSPECIFIED Algorithm = 0
	Algorithm_SHA1                       Algorithm = 1
	Algorithm_SHA256                     Algorithm = 2
	Algorithm_SHA512                     Algorithm = 3
	Algorithm_MD5                        Algorithm = 4
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_TYPE_UNSPECIFIED",
		1: "SHA1",
		2: "SHA256",
		3: "SHA512",
		4: "MD5",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_TYPE_UNSPECIFIED": 0,
		"SHA1":                       1,
		"SHA256":                     2,
		"SHA512":                     3,
		"MD5":                        4,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_OtpMigration_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_OtpMigration_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Algorithm) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Algorithm(num)
	return nil
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{0}
}

type DigitCount int32

const (
	DigitCount_DIGIT_COUNT_UNSPECIFIED DigitCount = 0
	DigitCount_SIX                     DigitCount = 1
	DigitCount_EIGHT                   DigitCount = 2
)

// Enum value maps for DigitCount.
var (
	DigitCount_name = map[int32]string{
		0: "DIGIT_COUNT_UNSPECIFIED",
		1: "SIX",
		2: "EIGHT",
	}
	DigitCount_value = map[string]int32{
		"DIGIT_COUNT_UNSPECIFIED": 0,
		"SIX":                     1,
		"EIGHT":                   2,
	}
)

func (x DigitCount) Enum() *DigitCount {
	p := new(DigitCount)
	*p = x
	return p
}

func (x DigitCount) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DigitCount) Descriptor() protoreflect.EnumDescriptor {
	return file_OtpMigration_proto_enumTypes[1].Descriptor()
}

func (DigitCount) Type() protoreflect.EnumType {
	return &file_OtpMigration_proto_enumTypes[1]
}

func (x DigitCount) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DigitCount) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DigitCount(num)
	return nil
}

// Deprecated: Use DigitCount.Descriptor instead.
func (DigitCount) EnumDescriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{1}
}

type OtpType int32

const (
	OtpType_OTP_TYPE_UNSPECIFIED OtpType = 0
	OtpType_HOTP                 OtpType = 1
	OtpType_TOTP                 OtpType = 2
)

// Enum value maps for OtpType.
var (
	OtpType_name = map[int32]string{
		0: "OTP_TYPE_UNSPECIFIED",
		1: "HOTP",
		2: "TOTP",
	}
	OtpType_value = map[string]int32{
		"OTP_TYPE_UNSPECIFIED": 0,
		"HOTP":                 1,
		"TOTP":                 2,
	}
)

func (x OtpType) Enum() *OtpType {
	p := new(OtpType)
	*p = x
	return p
}

func (x OtpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtpType) Descriptor() protoreflect.EnumDescriptor {
	return file_OtpMigration_proto_enumTypes[2].Descriptor()
}

func (OtpType) Type() protoreflect.EnumType {
	return &file_OtpMigration_proto_enumTypes[2]
}

func (x OtpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OtpType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OtpType(num)
	return nil
}

// Deprecated: Use OtpType.Descriptor instead.
func (OtpType) EnumDescriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{2}
}

type MigrationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpParameters []*OtpParameters       `protobuf:"bytes,1,rep,name=otp_parameters,json=otpParameters" json:"otp_parameters,omitempty"`
	Version       *int32                 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	BatchSize     *int32                 `protobuf:"varint,3,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	BatchIndex    *int32                 `protobuf:"varint,4,opt,name=batch_index,json=batchIndex" json:"batch_index,omitempty"`
	BatchId       *int32                 `protobuf:"varint,5,opt,name=batch_id,json=batchId" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationPayload) Reset() {
	*x = MigrationPayload{}
	mi := &file_OtpMigration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationPayload) ProtoMessage() {}

func (x *MigrationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_OtpMigration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationPayload.ProtoReflect.Descriptor instead.
func (*MigrationPayload) Descriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationPayload) GetOtpParameters() []*OtpParameters {
	if x != nil {
		return x.OtpParameters
	}
	return nil
}

func (x *MigrationPayload) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *MigrationPayload) GetBatchSize() int32 {
	if x != nil && x.BatchSize != nil {
		return *x.BatchSize
	}
	return 0
}

func (x *MigrationPayload) GetBatchIndex() int32 {
	if x != nil && x.BatchIndex != nil {
		return *x.BatchIndex
	}
	return 0
}

func (x *MigrationPayload) GetBatchId() int32 {
	if x != nil && x.BatchId != nil {
		return *x.BatchId
	}
	return 0
}

type OtpParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Issuer        *string                `protobuf:"bytes,3,opt,name=issuer" json:"issuer,omitempty"`
	Algorithm     *Algorithm             `protobuf:"varint,4,opt,name=algorithm,enum=Algorithm" json:"algorithm,omitempty"`
	Digits        *DigitCount            `protobuf:"varint,5,opt,name=digits,enum=DigitCount" json:"digits,omitempty"`
	Type          *OtpType               `protobuf:"varint,6,opt,name=type,enum=OtpType" json:"type,omitempty"`
	Counter       *int64                 `protobuf:"varint,7,opt,name=counter" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpParameters) Reset() {
	*x = OtpParameters{}
	mi := &file_OtpMigration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpParameters) ProtoMessage() {}

func (x *OtpParameters) ProtoReflect() protoreflect.Message {
	mi := &file_OtpMigration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpParameters.ProtoReflect.Descriptor instead.
func (*OtpParameters) Descriptor() ([]byte, []int) {
	return file_OtpMigration_proto_rawDescGZIP(), []int{1}
}

func (x *OtpParameters) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *OtpParameters) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OtpParameters) GetIssuer() string {
	if x != nil && x.Issuer != nil {
		return *x.Issuer
	}
	return ""
}

func (x *OtpParameters) GetAlgorithm() Algorithm {
	if x != nil && x.Algorithm != nil {
		return *x.Algorithm
	}
	return Algorithm_ALGORITHM_TYPE_UNSPECIFIED
}

func (x *OtpParameters) GetDigits() DigitCount {
	if x != nil && x.Digits != nil {
		return *x.Digits
	}
	return DigitCount_DIGIT_COUNT_UNSPECIFIED
}

func (x *OtpParameters) GetType() OtpType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return OtpType_OTP_TYPE_UNSPECIFIED
}

func (x *OtpParameters) GetCounter() int64 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

var File_OtpMigration_proto protoreflect.FileDescriptor

const file_OtpMigration_proto_rawDesc = "" +
	"\n" +
	"\x12OtpMigration.proto\"\xbe\x01\n" +
	"\x10MigrationPayload\x125\n" +
	"\x0eotp_parameters\x18\x01 \x03(\v2\x0e.OtpParametersR\rotpParameters\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12\x1f\n" +
	"\vbatch_index\x18\x04 \x01(\x05R\n" +
	"batchIndex\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\x05R\abatchId\"\xda\x01\n" +
	"\rOtpParameters\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12(\n" +
	"\talgorithm\x18\x04 \x01(\x0e2\n" +
	".AlgorithmR\talgorithm\x12#\n" +
	"\x06digits\x18\x05 \x01(\x0e2\v.DigitCountR\x06digits\x12\x1c\n" +
	"\x04type\x18\x06 \x01(\x0e2\b.OtpTypeR\x04type\x12\x18\n" +
	"\acounter\x18\a \x01(\x03R\acounter*V\n" +
	"\tAlgorithm\x12\x1e\n" +
	"\x1aALGORITHM_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04SHA1\x10\x01\x12\n" +
	"\n" +
	"\x06SHA256\x10\x02\x12\n" +
	"\n" +
	"\x06SHA512\x10\x03\x12\a\n" +
	"\x03MD5\x10\x04*=\n" +
	"\n" +
	"DigitCount\x12\x1b\n" +
	"\x17DIGIT_COUNT_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03SIX\x10\x01\x12\t\n" +
	"\x05EIGHT\x10\x02*7\n" +
	"\aOtpType\x12\x18\n" +
	"\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HOTP\x10\x01\x12\b\n" +
	"\x04TOTP\x10\x02B,Z*github.com/yourname/otpdecode/OtpMigration"

var (
	file_OtpMigration_proto_rawDescOnce sync.Once
	file_OtpMigration_proto_rawDescData []byte
)

func file_OtpMigration_proto_rawDescGZIP() []byte {
	file_OtpMigration_proto_rawDescOnce.Do(func() {
		file_OtpMigration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OtpMigration_proto_rawDesc), len(file_OtpMigration_proto_rawDesc)))
	})
	return file_OtpMigration_proto_rawDescData
}

var file_OtpMigration_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_OtpMigration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_OtpMigration_proto_goTypes = []any{
	(Algorithm)(0),           // 0: Algorithm
	(DigitCount)(0),          // 1: DigitCount
	(OtpType)(0),             // 2: OtpType
	(*MigrationPayload)(nil), // 3: MigrationPayload
	(*OtpParameters)(nil),    // 4: OtpParameters
}
var file_OtpMigration_proto_depIdxs = []int32{
	4, // 0: MigrationPayload.otp_parameters:type_name -> OtpParameters
	0, // 1: OtpParameters.algorithm:type_name -> Algorithm
	1, // 2: OtpParameters.digits:type_name -> DigitCount
	2, // 3: OtpParameters.type:type_name -> OtpType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_OtpMigration_proto_init() }
func file_OtpMigration_proto_init() {
	if File_OtpMigration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OtpMigration_proto_rawDesc), len(file_OtpMigration_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OtpMigration_proto_goTypes,
		DependencyIndexes: file_OtpMigration_proto_depIdxs,
		EnumInfos:         file_OtpMigration_proto_enumTypes,
		MessageInfos:      file_OtpMigration_proto_msgTypes,
	}.Build()
	File_OtpMigration_proto = out.File
	file_OtpMigration_proto_goTypes = nil
	file_OtpMigration_proto_depIdxs = nil
}
